package sun.util.resources;

public final class TimeZoneNames extends TimeZoneNamesBundle {
  protected final Object[][] getContents() {
    String[] arrayOfString1 = { "Acre Time", "ACT", "Acre Summer Time", "ACST", "Acre Time", "ACT" };
    String[] arrayOfString2 = { "Australian Central Standard Time (South Australia)", "ACST", "Australian Central Daylight Time (South Australia)", "ACDT", "Australian Central Time (South Australia)", "ACT" };
    String[] arrayOfString3 = { "Argentine Time", "ART", "Argentine Summer Time", "ARST", "Argentine Time", "ART" };
    String[] arrayOfString4 = { "Alaska Standard Time", "AKST", "Alaska Daylight Time", "AKDT", "Alaska Time", "AKT" };
    String[] arrayOfString5 = { "Amazon Time", "AMT", "Amazon Summer Time", "AMST", "Amazon Time", "AMT" };
    String[] arrayOfString6 = { "Arabia Standard Time", "AST", "Arabia Daylight Time", "ADT", "Arabia Time", "AT" };
    String[] arrayOfString7 = { "Armenia Time", "AMT", "Armenia Summer Time", "AMST", "Armenia Time", "AMT" };
    String[] arrayOfString8 = { "Atlantic Standard Time", "AST", "Atlantic Daylight Time", "ADT", "Atlantic Time", "AT" };
    String[] arrayOfString9 = { "Bangladesh Time", "BDT", "Bangladesh Summer Time", "BDST", "Bangladesh Time", "BDT" };
    String[] arrayOfString10 = { "Australian Eastern Standard Time (Queensland)", "AEST", "Australian Eastern Daylight Time (Queensland)", "AEDT", "Australian Eastern Time (Queensland)", "AET" };
    String[] arrayOfString11 = { "Australian Central Standard Time (South Australia/New South Wales)", "ACST", "Australian Central Daylight Time (South Australia/New South Wales)", "ACDT", "Australian Central Time (South Australia/New South Wales)", "ACT" };
    String[] arrayOfString12 = { "Brasilia Time", "BRT", "Brasilia Summer Time", "BRST", "Brasilia Time", "BRT" };
    String[] arrayOfString13 = { "Bhutan Time", "BTT", "Bhutan Summer Time", "BTST", "Bhutan Time", "BTT" };
    String[] arrayOfString14 = { "Central African Time", "CAT", "Central African Summer Time", "CAST", "Central Africa Time", "CAT" };
    String[] arrayOfString15 = { "Central European Time", "CET", "Central European Summer Time", "CEST", "Central European Time", "CET" };
    String[] arrayOfString16 = { "Chatham Standard Time", "CHAST", "Chatham Daylight Time", "CHADT", "Chatham Time", "CHAT" };
    String[] arrayOfString17 = { "Chuuk Time", "CHUT", "Chuuk Summer Time", "CHUST", "Chuuk Time", "CHUT" };
    String[] arrayOfString18 = { "Central Indonesia Time", "WITA", "Central Indonesia Summer Time", "CIST", "Central Indonesia Time", "WITA" };
    String[] arrayOfString19 = { "Chile Time", "CLT", "Chile Summer Time", "CLST", "Chile Time", "CLT" };
    String[] arrayOfString20 = { "Central Standard Time", "CST", "Central Daylight Time", "CDT", "Central Time", "CT" };
    String[] arrayOfString21 = { "China Standard Time", "CST", "China Daylight Time", "CDT", "China Time", "CT" };
    String[] arrayOfString22 = { "Cuba Standard Time", "CST", "Cuba Daylight Time", "CDT", "Cuba Time", "CT" };
    String[] arrayOfString23 = { "Australian Central Standard Time (Northern Territory)", "ACST", "Australian Central Daylight Time (Northern Territory)", "ACDT", "Australian Central Time (Northern Territory)", "ACT" };
    String[] arrayOfString24 = { "Greenwich Mean Time", "GMT", "Irish Summer Time", "IST", "Irish Time", "IT" };
    String[] arrayOfString25 = { "Eastern African Time", "EAT", "Eastern African Summer Time", "EAST", "Eastern Africa Time", "EAT" };
    String[] arrayOfString26 = { "Easter Is. Time", "EAST", "Easter Is. Summer Time", "EASST", "Easter Is. Time", "EAST" };
    String[] arrayOfString27 = { "Eastern European Time", "EET", "Eastern European Summer Time", "EEST", "Eastern European Time", "EET" };
    String[] arrayOfString28 = { "Eastern Greenland Time", "EGT", "Eastern Greenland Summer Time", "EGST", "Eastern Greenland Time", "EGT" };
    String[] arrayOfString29 = { "Eastern Standard Time", "EST", "Eastern Daylight Time", "EDT", "Eastern Time", "ET" };
    String[] arrayOfString30 = { "Australian Eastern Standard Time (New South Wales)", "AEST", "Australian Eastern Daylight Time (New South Wales)", "AEDT", "Australian Eastern Time (New South Wales)", "AET" };
    String[] arrayOfString31 = { "Further-eastern European Time", "FET", "Further-eastern European Summer Time", "FEST", "Further-eastern European Time", "FET" };
    String[] arrayOfString32 = { "Ghana Mean Time", "GMT", "Ghana Summer Time", "GHST", "Ghana Mean Time", "GMT" };
    String[] arrayOfString33 = { "Gambier Time", "GAMT", "Gambier Summer Time", "GAMST", "Gambier Time", "GAMT" };
    String[] arrayOfString34 = { "Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT", "Greenwich Mean Time", "GMT" };
    String[] arrayOfString35 = { "Greenwich Mean Time", "GMT", "British Summer Time", "BST", "British Time", "BT" };
    String[] arrayOfString36 = { "Gulf Standard Time", "GST", "Gulf Daylight Time", "GDT", "Gulf Time", "GT" };
    String[] arrayOfString37 = { "Hong Kong Time", "HKT", "Hong Kong Summer Time", "HKST", "Hong Kong Time", "HKT" };
    String[] arrayOfString38 = { "Hawaii Standard Time", "HST", "Hawaii Daylight Time", "HDT", "Hawaii Time", "HT" };
    String[] arrayOfString39 = { "Indochina Time", "ICT", "Indochina Summer Time", "ICST", "Indochina Time", "ICT" };
    String[] arrayOfString40 = { "Iran Standard Time", "IRST", "Iran Daylight Time", "IRDT", "Iran Time", "IRT" };
    String[] arrayOfString41 = { "Irkutsk Time", "IRKT", "Irkutsk Summer Time", "IRKST", "Irkutsk Time", "IRKT" };
    String[] arrayOfString42 = { "Israel Standard Time", "IST", "Israel Daylight Time", "IDT", "Israel Time", "IT" };
    String[] arrayOfString43 = { "India Standard Time", "IST", "India Daylight Time", "IDT", "India Time", "IT" };
    String[] arrayOfString44 = { "Japan Standard Time", "JST", "Japan Daylight Time", "JDT", "Japan Time", "JT" };
    String[] arrayOfString45 = { "Krasnoyarsk Time", "KRAT", "Krasnoyarsk Summer Time", "KRAST", "Krasnoyarsk Time", "KRAT" };
    String[] arrayOfString46 = { "Korea Standard Time", "KST", "Korea Daylight Time", "KDT", "Korea Time", "KT" };
    String[] arrayOfString47 = { "Lord Howe Standard Time", "LHST", "Lord Howe Daylight Time", "LHDT", "Lord Howe Time", "LHT" };
    String[] arrayOfString48 = { "Marshall Islands Time", "MHT", "Marshall Islands Summer Time", "MHST", "Marshall Islands Time", "MHT" };
    String[] arrayOfString49 = { "Moscow Standard Time", "MSK", "Moscow Daylight Time", "MSD", "Moscow Time", "MT" };
    String[] arrayOfString50 = { "Mountain Standard Time", "MST", "Mountain Daylight Time", "MDT", "Mountain Time", "MT" };
    String[] arrayOfString51 = { "Malaysia Time", "MYT", "Malaysia Summer Time", "MYST", "Malaysia Time", "MYT" };
    String[] arrayOfString52 = { "Fernando de Noronha Time", "FNT", "Fernando de Noronha Summer Time", "FNST", "Fernando de Noronha Time", "FNT" };
    String[] arrayOfString53 = { "Novosibirsk Time", "NOVT", "Novosibirsk Summer Time", "NOVST", "Novosibirsk Time", "NOVT" };
    String[] arrayOfString54 = { "Nepal Time", "NPT", "Nepal Summer Time", "NPST", "Nepal Time", "NPT" };
    String[] arrayOfString55 = { "Newfoundland Standard Time", "NST", "Newfoundland Daylight Time", "NDT", "Newfoundland Time", "NT" };
    String[] arrayOfString56 = { "New Zealand Standard Time", "NZST", "New Zealand Daylight Time", "NZDT", "New Zealand Time", "NZT" };
    String[] arrayOfString57 = { "Pitcairn Standard Time", "PST", "Pitcairn Daylight Time", "PDT", "Pitcairn Time", "PT" };
    String[] arrayOfString58 = { "Pakistan Time", "PKT", "Pakistan Summer Time", "PKST", "Pakistan Time", "PKT" };
    String[] arrayOfString59 = { "Pohnpei Time", "PONT", "Pohnpei Summer Time", "PONST", "Ponape Time", "PONT" };
    String[] arrayOfString60 = { "Pacific Standard Time", "PST", "Pacific Daylight Time", "PDT", "Pacific Time", "PT" };
    String[] arrayOfString61 = { "South Africa Standard Time", "SAST", "South Africa Summer Time", "SAST", "South Africa Time", "SAT" };
    String[] arrayOfString62 = { "Solomon Is. Time", "SBT", "Solomon Is. Summer Time", "SBST", "Solomon Is. Time", "SBT" };
    String[] arrayOfString63 = { "Singapore Time", "SGT", "Singapore Summer Time", "SGST", "Singapore Time", "SGT" };
    String[] arrayOfString64 = { "Australian Eastern Standard Time (Tasmania)", "AEST", "Australian Eastern Daylight Time (Tasmania)", "AEDT", "Australian Eastern Time (Tasmania)", "AET" };
    String[] arrayOfString65 = { "Turkmenistan Time", "TMT", "Turkmenistan Summer Time", "TMST", "Turkmenistan Time", "TMT" };
    String[] arrayOfString66 = { "Ulaanbaatar Time", "ULAT", "Ulaanbaatar Summer Time", "ULAST", "Ulaanbaatar Time", "ULAT" };
    String[] arrayOfString67 = { "Western African Time", "WAT", "Western African Summer Time", "WAST", "Western African Time", "WAT" };
    String[] arrayOfString68 = { "Western European Time", "WET", "Western European Summer Time", "WEST", "Western European Time", "WET" };
    String[] arrayOfString69 = { "West Indonesia Time", "WIB", "West Indonesia Summer Time", "WIST", "West Indonesia Time", "WIB" };
    String[] arrayOfString70 = { "Australian Western Standard Time", "AWST", "Australian Western Daylight Time", "AWDT", "Australian Western Time", "AWT" };
    String[] arrayOfString71 = { "Samoa Standard Time", "SST", "Samoa Daylight Time", "SDT", "Samoa Time", "ST" };
    String[] arrayOfString72 = { "West Samoa Standard Time", "WSST", "West Samoa Daylight Time", "WSDT", "West Samoa Time", "WST" };
    String[] arrayOfString73 = { "Chamorro Standard Time", "ChST", "Chamorro Daylight Time", "ChDT", "Chamorro Time", "ChT" };
    String[] arrayOfString74 = { "Australian Eastern Standard Time (Victoria)", "AEST", "Australian Eastern Daylight Time (Victoria)", "AEDT", "Australian Eastern Time (Victoria)", "AET" };
    String[] arrayOfString75 = { "Coordinated Universal Time", "UTC", "Coordinated Universal Time", "UTC", "Coordinated Universal Time", "UTC" };
    String[] arrayOfString76 = { "Uzbekistan Time", "UZT", "Uzbekistan Summer Time", "UZST", "Uzbekistan Time", "UZT" };
    String[] arrayOfString77 = { "Xinjiang Standard Time", "XJT", "Xinjiang Daylight Time", "XJDT", "Xinjiang Time", "XJT" };
    return new Object[][] { 
        { "America/Los_Angeles", arrayOfString60 }, { "PST", arrayOfString60 }, { "America/Denver", arrayOfString50 }, { "MST", arrayOfString50 }, { "America/Phoenix", arrayOfString50 }, { "PNT", arrayOfString50 }, { "America/Chicago", arrayOfString20 }, { "CST", arrayOfString20 }, { "America/New_York", arrayOfString29 }, { "EST", arrayOfString29 }, 
        { "America/Indianapolis", arrayOfString29 }, { "IET", arrayOfString29 }, { "Pacific/Honolulu", arrayOfString38 }, { "HST", arrayOfString38 }, { "America/Anchorage", arrayOfString4 }, { "AST", arrayOfString4 }, { "America/Halifax", arrayOfString8 }, { "America/Sitka", arrayOfString4 }, { "America/St_Johns", arrayOfString55 }, { "CNT", arrayOfString55 }, 
        { "Europe/Paris", arrayOfString15 }, { "ECT", arrayOfString15 }, { "GMT", arrayOfString34 }, { "Africa/Casablanca", arrayOfString68 }, { "Asia/Jerusalem", arrayOfString42 }, { "Asia/Tokyo", arrayOfString44 }, { "JST", arrayOfString44 }, { "Europe/Bucharest", arrayOfString27 }, { "Asia/Shanghai", arrayOfString21 }, { "CTT", arrayOfString21 }, 
        { "ACT", arrayOfString23 }, { "AET", arrayOfString30 }, { "AGT", arrayOfString3 }, { "ART", arrayOfString27 }, { "Africa/Abidjan", arrayOfString34 }, { "Africa/Accra", arrayOfString32 }, { "Africa/Addis_Ababa", arrayOfString25 }, { "Africa/Algiers", arrayOfString15 }, { "Africa/Asmara", arrayOfString25 }, { "Africa/Asmera", arrayOfString25 }, 
        { "Africa/Bamako", arrayOfString34 }, { "Africa/Bangui", arrayOfString67 }, { "Africa/Banjul", arrayOfString34 }, { "Africa/Bissau", arrayOfString34 }, { "Africa/Blantyre", arrayOfString14 }, { "Africa/Brazzaville", arrayOfString67 }, { "Africa/Bujumbura", arrayOfString14 }, { "Africa/Cairo", arrayOfString27 }, { "Africa/Ceuta", arrayOfString15 }, { "Africa/Conakry", arrayOfString34 }, 
        { "Africa/Dakar", arrayOfString34 }, { "Africa/Dar_es_Salaam", arrayOfString25 }, { "Africa/Djibouti", arrayOfString25 }, { "Africa/Douala", arrayOfString67 }, { "Africa/El_Aaiun", arrayOfString68 }, { "Africa/Freetown", arrayOfString34 }, { "Africa/Gaborone", arrayOfString14 }, { "Africa/Harare", arrayOfString14 }, { "Africa/Johannesburg", arrayOfString61 }, { "Africa/Juba", arrayOfString25 }, 
        { "Africa/Kampala", arrayOfString25 }, { "Africa/Khartoum", arrayOfString25 }, { "Africa/Kigali", arrayOfString14 }, { "Africa/Kinshasa", arrayOfString67 }, { "Africa/Lagos", arrayOfString67 }, { "Africa/Libreville", arrayOfString67 }, { "Africa/Lome", arrayOfString34 }, { "Africa/Luanda", arrayOfString67 }, { "Africa/Lubumbashi", arrayOfString14 }, { "Africa/Lusaka", arrayOfString14 }, 
        { "Africa/Malabo", arrayOfString67 }, { "Africa/Maputo", arrayOfString14 }, { "Africa/Maseru", arrayOfString61 }, { "Africa/Mbabane", arrayOfString61 }, { "Africa/Mogadishu", arrayOfString25 }, { "Africa/Monrovia", arrayOfString34 }, { "Africa/Nairobi", arrayOfString25 }, { "Africa/Ndjamena", arrayOfString67 }, { "Africa/Niamey", arrayOfString67 }, { "Africa/Nouakchott", arrayOfString34 }, 
        { "Africa/Ouagadougou", arrayOfString34 }, { "Africa/Porto-Novo", arrayOfString67 }, { "Africa/Sao_Tome", arrayOfString34 }, { "Africa/Timbuktu", arrayOfString34 }, { "Africa/Tripoli", arrayOfString27 }, { "Africa/Tunis", arrayOfString15 }, { "Africa/Windhoek", arrayOfString67 }, { "America/Adak", arrayOfString38 }, { "America/Anguilla", arrayOfString8 }, { "America/Antigua", arrayOfString8 }, 
        { "America/Araguaina", arrayOfString12 }, { "America/Argentina/Buenos_Aires", arrayOfString3 }, { "America/Argentina/Catamarca", arrayOfString3 }, { "America/Argentina/ComodRivadavia", arrayOfString3 }, { "America/Argentina/Cordoba", arrayOfString3 }, { "America/Argentina/Jujuy", arrayOfString3 }, { "America/Argentina/La_Rioja", arrayOfString3 }, { "America/Argentina/Mendoza", arrayOfString3 }, { "America/Argentina/Rio_Gallegos", arrayOfString3 }, { "America/Argentina/Salta", arrayOfString3 }, 
        { "America/Argentina/San_Juan", arrayOfString3 }, { "America/Argentina/San_Luis", arrayOfString3 }, { "America/Argentina/Tucuman", arrayOfString3 }, { "America/Argentina/Ushuaia", arrayOfString3 }, { "America/Aruba", arrayOfString8 }, { "America/Asuncion", { "Paraguay Time", "PYT", "Paraguay Summer Time", "PYST", "Paraguay Time", "PYT" } }, { "America/Atikokan", arrayOfString29 }, { "America/Atka", arrayOfString38 }, { "America/Bahia", arrayOfString12 }, { "America/Bahia_Banderas", arrayOfString20 }, 
        { "America/Barbados", arrayOfString8 }, { "America/Belem", arrayOfString12 }, { "America/Belize", arrayOfString20 }, { "America/Blanc-Sablon", arrayOfString8 }, { "America/Boa_Vista", arrayOfString5 }, { "America/Bogota", { "Colombia Time", "COT", "Colombia Summer Time", "COST", "Colombia Time", "COT" } }, { "America/Boise", arrayOfString50 }, { "America/Buenos_Aires", arrayOfString3 }, { "America/Cambridge_Bay", arrayOfString50 }, { "America/Campo_Grande", arrayOfString5 }, 
        { "America/Cancun", arrayOfString29 }, { "America/Caracas", { "Venezuela Time", "VET", "Venezuela Summer Time", "VEST", "Venezuela Time", "VET" } }, { "America/Catamarca", arrayOfString3 }, { "America/Cayenne", { "French Guiana Time", "GFT", "French Guiana Summer Time", "GFST", "French Guiana Time", "GFT" } }, { "America/Cayman", arrayOfString29 }, { "America/Chihuahua", arrayOfString50 }, { "America/Creston", arrayOfString50 }, { "America/Coral_Harbour", arrayOfString29 }, { "America/Cordoba", arrayOfString3 }, { "America/Costa_Rica", arrayOfString20 }, 
        { "America/Cuiaba", arrayOfString5 }, { "America/Curacao", arrayOfString8 }, { "America/Danmarkshavn", arrayOfString34 }, { "America/Dawson", arrayOfString60 }, { "America/Dawson_Creek", arrayOfString50 }, { "America/Detroit", arrayOfString29 }, { "America/Dominica", arrayOfString8 }, { "America/Edmonton", arrayOfString50 }, { "America/Eirunepe", arrayOfString1 }, { "America/El_Salvador", arrayOfString20 }, 
        { "America/Ensenada", arrayOfString60 }, { "America/Fort_Wayne", arrayOfString29 }, { "America/Fortaleza", arrayOfString12 }, { "America/Glace_Bay", arrayOfString8 }, { "America/Godthab", { "Western Greenland Time", "WGT", "Western Greenland Summer Time", "WGST", "Western Greenland Time", "WGT" } }, { "America/Goose_Bay", arrayOfString8 }, { "America/Grand_Turk", arrayOfString8 }, { "America/Grenada", arrayOfString8 }, { "America/Guadeloupe", arrayOfString8 }, { "America/Guatemala", arrayOfString20 }, 
        { "America/Guayaquil", { "Ecuador Time", "ECT", "Ecuador Summer Time", "ECST", "Ecuador Time", "ECT" } }, { "America/Guyana", { "Guyana Time", "GYT", "Guyana Summer Time", "GYST", "Guyana Time", "GYT" } }, { "America/Havana", arrayOfString22 }, { "America/Hermosillo", arrayOfString50 }, { "America/Indiana/Indianapolis", arrayOfString29 }, { "America/Indiana/Knox", arrayOfString20 }, { "America/Indiana/Marengo", arrayOfString29 }, { "America/Indiana/Petersburg", arrayOfString29 }, { "America/Indiana/Tell_City", arrayOfString20 }, { "America/Indiana/Vevay", arrayOfString29 }, 
        { "America/Indiana/Vincennes", arrayOfString29 }, { "America/Indiana/Winamac", arrayOfString29 }, { "America/Inuvik", arrayOfString50 }, { "America/Iqaluit", arrayOfString29 }, { "America/Jamaica", arrayOfString29 }, { "America/Jujuy", arrayOfString3 }, { "America/Juneau", arrayOfString4 }, { "America/Kentucky/Louisville", arrayOfString29 }, { "America/Kentucky/Monticello", arrayOfString29 }, { "America/Knox_IN", arrayOfString20 }, 
        { "America/Kralendijk", arrayOfString8 }, { "America/La_Paz", { "Bolivia Time", "BOT", "Bolivia Summer Time", "BOST", "Bolivia Time", "BOT" } }, { "America/Lima", { "Peru Time", "PET", "Peru Summer Time", "PEST", "Peru Time", "PET" } }, { "America/Louisville", arrayOfString29 }, { "America/Lower_Princes", arrayOfString8 }, { "America/Maceio", arrayOfString12 }, { "America/Managua", arrayOfString20 }, { "America/Manaus", arrayOfString5 }, { "America/Marigot", arrayOfString8 }, { "America/Martinique", arrayOfString8 }, 
        { "America/Matamoros", arrayOfString20 }, { "America/Mazatlan", arrayOfString50 }, { "America/Mendoza", arrayOfString3 }, { "America/Menominee", arrayOfString20 }, { "America/Merida", arrayOfString20 }, { "America/Metlakatla", arrayOfString60 }, { "America/Mexico_City", arrayOfString20 }, { "America/Miquelon", { "Pierre & Miquelon Standard Time", "PMST", "Pierre & Miquelon Daylight Time", "PMDT", "Pierre & Miquelon Time", "PMT" } }, { "America/Moncton", arrayOfString8 }, { "America/Montevideo", { "Uruguay Time", "UYT", "Uruguay Summer Time", "UYST", "Uruguay Time", "UYT" } }, 
        { "America/Monterrey", arrayOfString20 }, { "America/Montreal", arrayOfString29 }, { "America/Montserrat", arrayOfString8 }, { "America/Nassau", arrayOfString29 }, { "America/Nipigon", arrayOfString29 }, { "America/Nome", arrayOfString4 }, { "America/Noronha", arrayOfString52 }, { "America/North_Dakota/Beulah", arrayOfString20 }, { "America/North_Dakota/Center", arrayOfString20 }, { "America/North_Dakota/New_Salem", arrayOfString20 }, 
        { "America/Ojinaga", arrayOfString50 }, { "America/Panama", arrayOfString29 }, { "America/Pangnirtung", arrayOfString29 }, { "America/Paramaribo", { "Suriname Time", "SRT", "Suriname Summer Time", "SRST", "Suriname Time", "SRT" } }, { "America/Port-au-Prince", arrayOfString29 }, { "America/Port_of_Spain", arrayOfString8 }, { "America/Porto_Acre", arrayOfString1 }, { "America/Porto_Velho", arrayOfString5 }, { "America/Puerto_Rico", arrayOfString8 }, { "America/Rainy_River", arrayOfString20 }, 
        { "America/Rankin_Inlet", arrayOfString20 }, { "America/Recife", arrayOfString12 }, { "America/Regina", arrayOfString20 }, { "America/Resolute", arrayOfString20 }, { "America/Rio_Branco", arrayOfString1 }, { "America/Rosario", arrayOfString3 }, { "America/Santa_Isabel", arrayOfString60 }, { "America/Santarem", arrayOfString12 }, { "America/Santiago", arrayOfString19 }, { "America/Santo_Domingo", arrayOfString8 }, 
        { "America/Sao_Paulo", arrayOfString12 }, { "America/Scoresbysund", arrayOfString28 }, { "America/Shiprock", arrayOfString50 }, { "America/St_Barthelemy", arrayOfString8 }, { "America/St_Kitts", arrayOfString8 }, { "America/St_Lucia", arrayOfString8 }, { "America/St_Thomas", arrayOfString8 }, { "America/St_Vincent", arrayOfString8 }, { "America/Swift_Current", arrayOfString20 }, { "America/Tegucigalpa", arrayOfString20 }, 
        { "America/Thule", arrayOfString8 }, { "America/Thunder_Bay", arrayOfString29 }, { "America/Tijuana", arrayOfString60 }, { "America/Toronto", arrayOfString29 }, { "America/Tortola", arrayOfString8 }, { "America/Vancouver", arrayOfString60 }, { "America/Virgin", arrayOfString8 }, { "America/Whitehorse", arrayOfString60 }, { "America/Winnipeg", arrayOfString20 }, { "America/Yakutat", arrayOfString4 }, 
        { "America/Yellowknife", arrayOfString50 }, { "Antarctica/Casey", arrayOfString70 }, { "Antarctica/Davis", { "Davis Time", "DAVT", "Davis Summer Time", "DAVST", "Davis Time", "DAVT" } }, { "Antarctica/DumontDUrville", { "Dumont-d'Urville Time", "DDUT", "Dumont-d'Urville Summer Time", "DDUST", "Dumont-d'Urville Time", "DDUT" } }, { "Antarctica/Macquarie", { "Macquarie Island Standard Time", "MIST", "Macquarie Island Daylight Time", "MIDT", "Macquarie Island Time", "MIST" } }, { "Antarctica/Mawson", { "Mawson Time", "MAWT", "Mawson Summer Time", "MAWST", "Mawson Time", "MAWT" } }, { "Antarctica/McMurdo", arrayOfString56 }, { "Antarctica/Palmer", arrayOfString19 }, { "Antarctica/Rothera", { "Rothera Time", "ROTT", "Rothera Summer Time", "ROTST", "Rothera Time", "ROTT" } }, { "Antarctica/South_Pole", arrayOfString56 }, 
        { "Antarctica/Syowa", { "Syowa Time", "SYOT", "Syowa Summer Time", "SYOST", "Syowa Time", "SYOT" } }, { "Antarctica/Troll", { "Coordinated Universal Time", "UTC", "Central European Summer Time", "CEST", "Troll Time", "ATT" } }, { "Antarctica/Vostok", { "Vostok Time", "VOST", "Vostok Summer Time", "VOSST", "Vostok Time", "VOST" } }, { "Arctic/Longyearbyen", arrayOfString15 }, { "Asia/Aden", arrayOfString6 }, { "Asia/Almaty", { "Alma-Ata Time", "ALMT", "Alma-Ata Summer Time", "ALMST", "Alma-Ata Time", "ALMT" } }, { "Asia/Amman", arrayOfString27 }, { "Asia/Anadyr", { "Anadyr Time", "ANAT", "Anadyr Summer Time", "ANAST", "Anadyr Time", "ANAT" } }, { "Asia/Aqtau", { "Aqtau Time", "AQTT", "Aqtau Summer Time", "AQTST", "Aqtau Time", "AQTT" } }, { "Asia/Aqtobe", { "Aqtobe Time", "AQTT", "Aqtobe Summer Time", "AQTST", "Aqtobe Time", "AQTT" } }, 
        { "Asia/Ashgabat", arrayOfString65 }, { "Asia/Ashkhabad", arrayOfString65 }, { "Asia/Baghdad", arrayOfString6 }, { "Asia/Bahrain", arrayOfString6 }, { "Asia/Baku", { "Azerbaijan Time", "AZT", "Azerbaijan Summer Time", "AZST", "Azerbaijan Time", "AZT" } }, { "Asia/Bangkok", arrayOfString39 }, { "Asia/Beirut", arrayOfString27 }, { "Asia/Bishkek", { "Kirgizstan Time", "KGT", "Kirgizstan Summer Time", "KGST", "Kirgizstan Time", "KGT" } }, { "Asia/Brunei", { "Brunei Time", "BNT", "Brunei Summer Time", "BNST", "Brunei Time", "BNT" } }, { "Asia/Calcutta", arrayOfString43 }, 
        { "Asia/Chita", arrayOfString41 }, { "Asia/Choibalsan", { "Choibalsan Time", "CHOT", "Choibalsan Summer Time", "CHOST", "Choibalsan Time", "CHOT" } }, { "Asia/Chongqing", arrayOfString21 }, { "Asia/Chungking", arrayOfString21 }, { "Asia/Colombo", arrayOfString43 }, { "Asia/Dacca", arrayOfString9 }, { "Asia/Dhaka", arrayOfString9 }, { "Asia/Dili", { "Timor-Leste Time", "TLT", "Timor-Leste Summer Time", "TLST", "Timor-Leste Time", "TLT" } }, { "Asia/Damascus", arrayOfString27 }, { "Asia/Dubai", arrayOfString36 }, 
        { "Asia/Dushanbe", { "Tajikistan Time", "TJT", "Tajikistan Summer Time", "TJST", "Tajikistan Time", "TJT" } }, { "Asia/Gaza", arrayOfString27 }, { "Asia/Harbin", arrayOfString21 }, { "Asia/Hebron", arrayOfString27 }, { "Asia/Ho_Chi_Minh", arrayOfString39 }, { "Asia/Hong_Kong", arrayOfString37 }, { "Asia/Hovd", { "Hovd Time", "HOVT", "Hovd Summer Time", "HOVST", "Hovd Time", "HOVT" } }, { "Asia/Irkutsk", arrayOfString41 }, { "Asia/Istanbul", arrayOfString27 }, { "Asia/Jakarta", arrayOfString69 }, 
        { "Asia/Jayapura", { "East Indonesia Time", "WIT", "East Indonesia Summer Time", "EIST", "East Indonesia Time", "WIT" } }, { "Asia/Kabul", { "Afghanistan Time", "AFT", "Afghanistan Summer Time", "AFST", "Afghanistan Time", "AFT" } }, { "Asia/Kamchatka", { "Petropavlovsk-Kamchatski Time", "PETT", "Petropavlovsk-Kamchatski Summer Time", "PETST", "Petropavlovsk-Kamchatski Time", "PETT" } }, { "Asia/Karachi", arrayOfString58 }, { "Asia/Kashgar", arrayOfString77 }, { "Asia/Kathmandu", arrayOfString54 }, { "Asia/Katmandu", arrayOfString54 }, { "Asia/Khandyga", { "Khandyga Time", "YAKT", "Khandyga Summer Time", "YAKST", "Khandyga Time", "YAKT" } }, { "Asia/Kolkata", arrayOfString43 }, { "Asia/Krasnoyarsk", arrayOfString45 }, 
        { "Asia/Kuala_Lumpur", arrayOfString51 }, { "Asia/Kuching", arrayOfString51 }, { "Asia/Kuwait", arrayOfString6 }, { "Asia/Macao", arrayOfString21 }, { "Asia/Macau", arrayOfString21 }, { "Asia/Magadan", { "Magadan Time", "MAGT", "Magadan Summer Time", "MAGST", "Magadan Time", "MAGT" } }, { "Asia/Makassar", arrayOfString18 }, { "Asia/Manila", { "Philippines Time", "PHT", "Philippines Summer Time", "PHST", "Philippines Time", "PHT" } }, { "Asia/Muscat", arrayOfString36 }, { "Asia/Nicosia", arrayOfString27 }, 
        { "Asia/Novokuznetsk", arrayOfString45 }, { "Asia/Novosibirsk", arrayOfString53 }, { "Asia/Oral", { "Oral Time", "ORAT", "Oral Summer Time", "ORAST", "Oral Time", "ORAT" } }, { "Asia/Omsk", { "Omsk Time", "OMST", "Omsk Summer Time", "OMSST", "Omsk Time", "OMST" } }, { "Asia/Phnom_Penh", arrayOfString39 }, { "Asia/Pontianak", arrayOfString69 }, { "Asia/Pyongyang", arrayOfString46 }, { "Asia/Qatar", arrayOfString6 }, { "Asia/Qyzylorda", { "Qyzylorda Time", "QYZT", "Qyzylorda Summer Time", "QYZST", "Qyzylorda Time", "QYZT" } }, { "Asia/Rangoon", { "Myanmar Time", "MMT", "Myanmar Summer Time", "MMST", "Myanmar Time", "MMT" } }, 
        { "Asia/Riyadh", arrayOfString6 }, { "Asia/Saigon", arrayOfString39 }, { "Asia/Sakhalin", { "Sakhalin Time", "SAKT", "Sakhalin Summer Time", "SAKST", "Sakhalin Time", "SAKT" } }, { "Asia/Samarkand", arrayOfString76 }, { "Asia/Seoul", arrayOfString46 }, { "Asia/Singapore", arrayOfString63 }, { "Asia/Srednekolymsk", { "Srednekolymsk Time", "SRET", "Srednekolymsk Daylight Time", "SREDT", "Srednekolymsk Time", "SRET" } }, { "Asia/Taipei", arrayOfString21 }, { "Asia/Tel_Aviv", arrayOfString42 }, { "Asia/Tashkent", arrayOfString76 }, 
        { "Asia/Tbilisi", { "Georgia Time", "GET", "Georgia Summer Time", "GEST", "Georgia Time", "GET" } }, { "Asia/Tehran", arrayOfString40 }, { "Asia/Thimbu", arrayOfString13 }, { "Asia/Thimphu", arrayOfString13 }, { "Asia/Ujung_Pandang", arrayOfString18 }, { "Asia/Ulaanbaatar", arrayOfString66 }, { "Asia/Ulan_Bator", arrayOfString66 }, { "Asia/Urumqi", arrayOfString77 }, { "Asia/Ust-Nera", { "Ust-Nera Time", "VLAT", "Ust-Nera Summer Time", "VLAST", "Ust-Nera Time", "VLAT" } }, { "Asia/Vientiane", arrayOfString39 }, 
        { "Asia/Vladivostok", { "Vladivostok Time", "VLAT", "Vladivostok Summer Time", "VLAST", "Vladivostok Time", "VLAT" } }, { "Asia/Yakutsk", { "Yakutsk Time", "YAKT", "Yakutsk Summer Time", "YAKST", "Yakutsk Time", "YAKT" } }, { "Asia/Yekaterinburg", { "Yekaterinburg Time", "YEKT", "Yekaterinburg Summer Time", "YEKST", "Yekaterinburg Time", "YEKT" } }, { "Asia/Yerevan", arrayOfString7 }, { "Atlantic/Azores", { "Azores Time", "AZOT", "Azores Summer Time", "AZOST", "Azores Time", "AZOT" } }, { "Atlantic/Bermuda", arrayOfString8 }, { "Atlantic/Canary", arrayOfString68 }, { "Atlantic/Cape_Verde", { "Cape Verde Time", "CVT", "Cape Verde Summer Time", "CVST", "Cape Verde Time", "CVT" } }, { "Atlantic/Faeroe", arrayOfString68 }, { "Atlantic/Faroe", arrayOfString68 }, 
        { "Atlantic/Jan_Mayen", arrayOfString15 }, { "Atlantic/Madeira", arrayOfString68 }, { "Atlantic/Reykjavik", arrayOfString34 }, { "Atlantic/South_Georgia", { "South Georgia Standard Time", "GST", "South Georgia Daylight Time", "GDT", "South Georgia Time", "GT" } }, { "Atlantic/St_Helena", arrayOfString34 }, { "Atlantic/Stanley", { "Falkland Is. Time", "FKT", "Falkland Is. Summer Time", "FKST", "Falkland Is. Time", "FKT" } }, { "Australia/ACT", arrayOfString30 }, { "Australia/Adelaide", arrayOfString2 }, { "Australia/Brisbane", arrayOfString10 }, { "Australia/Broken_Hill", arrayOfString11 }, 
        { "Australia/Canberra", arrayOfString30 }, { "Australia/Currie", arrayOfString30 }, { "Australia/Darwin", arrayOfString23 }, { "Australia/Eucla", { "Australian Central Western Standard Time", "ACWST", "Australian Central Western Daylight Time", "ACWDT", "Australian Central Western Time", "ACWT" } }, { "Australia/Hobart", arrayOfString64 }, { "Australia/LHI", arrayOfString47 }, { "Australia/Lindeman", arrayOfString10 }, { "Australia/Lord_Howe", arrayOfString47 }, { "Australia/Melbourne", arrayOfString74 }, { "Australia/North", arrayOfString23 }, 
        { "Australia/NSW", arrayOfString30 }, { "Australia/Perth", arrayOfString70 }, { "Australia/Queensland", arrayOfString10 }, { "Australia/South", arrayOfString2 }, { "Australia/Sydney", arrayOfString30 }, { "Australia/Tasmania", arrayOfString64 }, { "Australia/Victoria", arrayOfString74 }, { "Australia/West", arrayOfString70 }, { "Australia/Yancowinna", arrayOfString11 }, { "BET", arrayOfString12 }, 
        { "BST", arrayOfString9 }, { "Brazil/Acre", arrayOfString1 }, { "Brazil/DeNoronha", arrayOfString52 }, { "Brazil/East", arrayOfString12 }, { "Brazil/West", arrayOfString5 }, { "Canada/Atlantic", arrayOfString8 }, { "Canada/Central", arrayOfString20 }, { "Canada/East-Saskatchewan", arrayOfString20 }, { "Canada/Eastern", arrayOfString29 }, { "Canada/Mountain", arrayOfString50 }, 
        { "Canada/Newfoundland", arrayOfString55 }, { "Canada/Pacific", arrayOfString60 }, { "Canada/Yukon", arrayOfString60 }, { "Canada/Saskatchewan", arrayOfString20 }, { "CAT", arrayOfString14 }, { "CET", arrayOfString15 }, { "Chile/Continental", arrayOfString19 }, { "Chile/EasterIsland", arrayOfString26 }, { "CST6CDT", arrayOfString20 }, { "Cuba", arrayOfString22 }, 
        { "EAT", arrayOfString25 }, { "EET", arrayOfString27 }, { "Egypt", arrayOfString27 }, { "Eire", arrayOfString24 }, { "EST5EDT", arrayOfString29 }, { "Etc/Greenwich", arrayOfString34 }, { "Etc/UCT", arrayOfString75 }, { "Etc/Universal", arrayOfString75 }, { "Etc/UTC", arrayOfString75 }, { "Etc/Zulu", arrayOfString75 }, 
        { "Europe/Amsterdam", arrayOfString15 }, { "Europe/Andorra", arrayOfString15 }, { "Europe/Athens", arrayOfString27 }, { "Europe/Belfast", arrayOfString35 }, { "Europe/Belgrade", arrayOfString15 }, { "Europe/Berlin", arrayOfString15 }, { "Europe/Bratislava", arrayOfString15 }, { "Europe/Brussels", arrayOfString15 }, { "Europe/Budapest", arrayOfString15 }, { "Europe/Busingen", arrayOfString15 }, 
        { "Europe/Chisinau", arrayOfString27 }, { "Europe/Copenhagen", arrayOfString15 }, { "Europe/Dublin", arrayOfString24 }, { "Europe/Gibraltar", arrayOfString15 }, { "Europe/Guernsey", arrayOfString35 }, { "Europe/Helsinki", arrayOfString27 }, { "Europe/Isle_of_Man", arrayOfString35 }, { "Europe/Istanbul", arrayOfString27 }, { "Europe/Jersey", arrayOfString35 }, { "Europe/Kaliningrad", arrayOfString27 }, 
        { "Europe/Kiev", arrayOfString27 }, { "Europe/Lisbon", arrayOfString68 }, { "Europe/Ljubljana", arrayOfString15 }, { "Europe/London", arrayOfString35 }, { "Europe/Luxembourg", arrayOfString15 }, { "Europe/Madrid", arrayOfString15 }, { "Europe/Malta", arrayOfString15 }, { "Europe/Mariehamn", arrayOfString27 }, { "Europe/Minsk", arrayOfString49 }, { "Europe/Monaco", arrayOfString15 }, 
        { "Europe/Moscow", arrayOfString49 }, { "Europe/Nicosia", arrayOfString27 }, { "Europe/Oslo", arrayOfString15 }, { "Europe/Podgorica", arrayOfString15 }, { "Europe/Prague", arrayOfString15 }, { "Europe/Riga", arrayOfString27 }, { "Europe/Rome", arrayOfString15 }, { "Europe/Samara", { "Samara Time", "SAMT", "Samara Summer Time", "SAMST", "Samara Time", "SAMT" } }, { "Europe/San_Marino", arrayOfString15 }, { "Europe/Sarajevo", arrayOfString15 }, 
        { "Europe/Simferopol", arrayOfString49 }, { "Europe/Skopje", arrayOfString15 }, { "Europe/Sofia", arrayOfString27 }, { "Europe/Stockholm", arrayOfString15 }, { "Europe/Tallinn", arrayOfString27 }, { "Europe/Tirane", arrayOfString15 }, { "Europe/Tiraspol", arrayOfString27 }, { "Europe/Uzhgorod", arrayOfString27 }, { "Europe/Vaduz", arrayOfString15 }, { "Europe/Vatican", arrayOfString15 }, 
        { "Europe/Vienna", arrayOfString15 }, { "Europe/Vilnius", arrayOfString27 }, { "Europe/Volgograd", arrayOfString49 }, { "Europe/Warsaw", arrayOfString15 }, { "Europe/Zagreb", arrayOfString15 }, { "Europe/Zaporozhye", arrayOfString27 }, { "Europe/Zurich", arrayOfString15 }, { "GB", arrayOfString35 }, { "GB-Eire", arrayOfString35 }, { "Greenwich", arrayOfString34 }, 
        { "Hongkong", arrayOfString37 }, { "Iceland", arrayOfString34 }, { "Iran", arrayOfString40 }, { "IST", arrayOfString43 }, { "Indian/Antananarivo", arrayOfString25 }, { "Indian/Chagos", { "Indian Ocean Territory Time", "IOT", "Indian Ocean Territory Summer Time", "IOST", "Indian Ocean Territory Time", "IOT" } }, { "Indian/Christmas", { "Christmas Island Time", "CXT", "Christmas Island Summer Time", "CXST", "Christmas Island Time", "CIT" } }, { "Indian/Cocos", { "Cocos Islands Time", "CCT", "Cocos Islands Summer Time", "CCST", "Cocos Islands Time", "CCT" } }, { "Indian/Comoro", arrayOfString25 }, { "Indian/Kerguelen", { "French Southern & Antarctic Lands Time", "TFT", "French Southern & Antarctic Lands Summer Time", "TFST", "French Southern & Antarctic Lands Time", "TFT" } }, 
        { "Indian/Mahe", { "Seychelles Time", "SCT", "Seychelles Summer Time", "SCST", "Seychelles Time", "SCT" } }, { "Indian/Maldives", { "Maldives Time", "MVT", "Maldives Summer Time", "MVST", "Maldives Time", "MVT" } }, { "Indian/Mauritius", { "Mauritius Time", "MUT", "Mauritius Summer Time", "MUST", "Mauritius Time", "MUT" } }, { "Indian/Mayotte", arrayOfString25 }, { "Indian/Reunion", { "Reunion Time", "RET", "Reunion Summer Time", "REST", "Reunion Time", "RET" } }, { "Israel", arrayOfString42 }, { "Jamaica", arrayOfString29 }, { "Japan", arrayOfString44 }, { "Kwajalein", arrayOfString48 }, { "Libya", arrayOfString27 }, 
        { "MET", { "Middle Europe Time", "MET", "Middle Europe Summer Time", "MEST", "Middle Europe Time", "MET" } }, { "Mexico/BajaNorte", arrayOfString60 }, { "Mexico/BajaSur", arrayOfString50 }, { "Mexico/General", arrayOfString20 }, { "MIT", arrayOfString72 }, { "MST7MDT", arrayOfString50 }, { "Navajo", arrayOfString50 }, { "NET", arrayOfString7 }, { "NST", arrayOfString56 }, { "NZ", arrayOfString56 }, 
        { "NZ-CHAT", arrayOfString16 }, { "PLT", arrayOfString58 }, { "Portugal", arrayOfString68 }, { "PRT", arrayOfString8 }, { "Pacific/Apia", arrayOfString72 }, { "Pacific/Auckland", arrayOfString56 }, { "Pacific/Bougainville", { "Bougainville Standard Time", "BST", "Bougainville Daylight Time", "BST", "Bougainville Time", "BT" } }, { "Pacific/Chatham", arrayOfString16 }, { "Pacific/Chuuk", arrayOfString17 }, { "Pacific/Easter", arrayOfString26 }, 
        { "Pacific/Efate", { "Vanuatu Time", "VUT", "Vanuatu Summer Time", "VUST", "Vanuatu Time", "VUT" } }, { "Pacific/Enderbury", { "Phoenix Is. Time", "PHOT", "Phoenix Is. Summer Time", "PHOST", "Phoenix Is. Time", "PHOT" } }, { "Pacific/Fakaofo", { "Tokelau Time", "TKT", "Tokelau Summer Time", "TKST", "Tokelau Time", "TKT" } }, { "Pacific/Fiji", { "Fiji Time", "FJT", "Fiji Summer Time", "FJST", "Fiji Time", "FJT" } }, { "Pacific/Funafuti", { "Tuvalu Time", "TVT", "Tuvalu Summer Time", "TVST", "Tuvalu Time", "TVT" } }, { "Pacific/Galapagos", { "Galapagos Time", "GALT", "Galapagos Summer Time", "GALST", "Galapagos Time", "GALT" } }, { "Pacific/Gambier", arrayOfString33 }, { "Pacific/Guadalcanal", arrayOfString62 }, { "Pacific/Guam", arrayOfString73 }, { "Pacific/Johnston", arrayOfString38 }, 
        { "Pacific/Kiritimati", { "Line Is. Time", "LINT", "Line Is. Summer Time", "LINST", "Line Is. Time", "LINT" } }, { "Pacific/Kosrae", { "Kosrae Time", "KOST", "Kosrae Summer Time", "KOSST", "Kosrae Time", "KOST" } }, { "Pacific/Kwajalein", arrayOfString48 }, { "Pacific/Majuro", arrayOfString48 }, { "Pacific/Marquesas", { "Marquesas Time", "MART", "Marquesas Summer Time", "MARST", "Marquesas Time", "MART" } }, { "Pacific/Midway", arrayOfString71 }, { "Pacific/Nauru", { "Nauru Time", "NRT", "Nauru Summer Time", "NRST", "Nauru Time", "NRT" } }, { "Pacific/Niue", { "Niue Time", "NUT", "Niue Summer Time", "NUST", "Niue Time", "NUT" } }, { "Pacific/Norfolk", { "Norfolk Time", "NFT", "Norfolk Summer Time", "NFST", "Norfolk Time", "NFT" } }, { "Pacific/Noumea", { "New Caledonia Time", "NCT", "New Caledonia Summer Time", "NCST", "New Caledonia Time", "NCT" } }, 
        { "Pacific/Pago_Pago", arrayOfString71 }, { "Pacific/Palau", { "Palau Time", "PWT", "Palau Summer Time", "PWST", "Palau Time", "PWT" } }, { "Pacific/Pitcairn", arrayOfString57 }, { "Pacific/Pohnpei", arrayOfString59 }, { "Pacific/Ponape", arrayOfString59 }, { "Pacific/Port_Moresby", { "Papua New Guinea Time", "PGT", "Papua New Guinea Summer Time", "PGST", "Papua New Guinea Time", "PGT" } }, { "Pacific/Rarotonga", { "Cook Is. Time", "CKT", "Cook Is. Summer Time", "CKHST", "Cook Is. Time", "CKT" } }, { "Pacific/Saipan", arrayOfString73 }, { "Pacific/Samoa", arrayOfString71 }, { "Pacific/Tahiti", { "Tahiti Time", "TAHT", "Tahiti Summer Time", "TAHST", "Tahiti Time", "TAHT" } }, 
        { "Pacific/Tarawa", { "Gilbert Is. Time", "GILT", "Gilbert Is. Summer Time", "GILST", "Gilbert Is. Time", "GILT" } }, { "Pacific/Tongatapu", { "Tonga Time", "TOT", "Tonga Summer Time", "TOST", "Tonga Time", "TOT" } }, { "Pacific/Truk", arrayOfString17 }, { "Pacific/Wake", { "Wake Time", "WAKT", "Wake Summer Time", "WAKST", "Wake Time", "WAKT" } }, { "Pacific/Wallis", { "Wallis & Futuna Time", "WFT", "Wallis & Futuna Summer Time", "WFST", "Wallis & Futuna Time", "WFT" } }, { "Pacific/Yap", arrayOfString17 }, { "Poland", arrayOfString15 }, { "PRC", arrayOfString21 }, { "PST8PDT", arrayOfString60 }, { "ROK", arrayOfString46 }, 
        { "Singapore", arrayOfString63 }, { "SST", arrayOfString62 }, { "SystemV/AST4", arrayOfString8 }, { "SystemV/AST4ADT", arrayOfString8 }, { "SystemV/CST6", arrayOfString20 }, { "SystemV/CST6CDT", arrayOfString20 }, { "SystemV/EST5", arrayOfString29 }, { "SystemV/EST5EDT", arrayOfString29 }, { "SystemV/HST10", arrayOfString38 }, { "SystemV/MST7", arrayOfString50 }, 
        { "SystemV/MST7MDT", arrayOfString50 }, { "SystemV/PST8", arrayOfString60 }, { "SystemV/PST8PDT", arrayOfString60 }, { "SystemV/YST9", arrayOfString4 }, { "SystemV/YST9YDT", arrayOfString4 }, { "Turkey", arrayOfString27 }, { "UCT", arrayOfString75 }, { "Universal", arrayOfString75 }, { "US/Alaska", arrayOfString4 }, { "US/Aleutian", arrayOfString38 }, 
        { "US/Arizona", arrayOfString50 }, { "US/Central", arrayOfString20 }, { "US/Eastern", arrayOfString29 }, { "US/Hawaii", arrayOfString38 }, { "US/Indiana-Starke", arrayOfString20 }, { "US/East-Indiana", arrayOfString29 }, { "US/Michigan", arrayOfString29 }, { "US/Mountain", arrayOfString50 }, { "US/Pacific", arrayOfString60 }, { "US/Pacific-New", arrayOfString60 }, 
        { "US/Samoa", arrayOfString71 }, { "UTC", arrayOfString75 }, { "VST", arrayOfString39 }, { "W-SU", arrayOfString49 }, { "WET", arrayOfString68 }, { "Zulu", arrayOfString75 } };
  }
}
